### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by alexmc1510** [onewayautomation/ogamma-logger#1]
Hello,

I have followed all your installation steps and I have found 2 errors:
- When I download the master zip, the other 2 zip inside are empty. The workaround I have applied is to download zips individually.
- When I click on OPCUADataLogger.exe a cmd black screen appears and closes immediately so I cannot read anything.

Finally, it doesn't work.

Could you have a look?

Regards,

**Comment by RavilN** [comment]
Hi,
Thank you for reporting this issue!
Yes, I see that the master zip file have other 2 zip files inside empty. I think it is something to do with how GitHub creates master zip from repository, which includes zip file inside. Probably the reason is because those 2 zip files are stored using large file storage mechanism. I will update instructions to not use master zip file.
Could you please clarify, do you have both Visual C++ 2017 and 2013 redistributables installed? 
And did you unzip file binaries.zip into the same folder as opcua-logger.zip, so the exe and all DLLs are in the same folder.
If yes, then I will need more info about error. I think that you were starting the exe from Windows explorer, therefore cannot read error message reported. Could you please open Windows console, navigate to the folder where OpcUaLogger.exe is located, and try to start it from command line, and let me know what is the error message.
As well as would be good to know what is the Windows OS version you are using.
Thank you, Ravil

**Comment by RavilN** [comment]
Updated ReadMe with instructions to install both Visual C++ 2013 and 2017 redistributables; 
Removed binaries.zip file, now all DLLs are included into single zip file. Verified that it works on fresh VM (Windows 10)
alexmc1510, if you could try to install and run it again, would be great.

**Comment by alexmc1510** [comment]
Hello RavinlN,

Thank you in advance for your support. Finally I was able to install and try it during weekend using the first method and it works!!
I have also programmed a group of tags (100) but I have some doubts regarding configuration:
- I don't know which method is better for reading (poll or suscribe).
- I can see that every reading, only stores 2 values at the same time. Could be related to queue size?
- I have checked automatic restore after OPC UA server disconnection and it doesn't work.

If you want I can help you with the development. I am very interested on this software and it's a great idea.

Thanks,

**Comment by RavilN** [comment]
Hi alexmc1510,
Currently only subscribe is supported, I will create issue about polling being not supported later.

About storing of only 2 values, I did not understand. It should store values whenever publish response with values is received from the server. If the response has only 2 values, then only those will be stored. There is no caching or other kind of optimization. Number of values per a variable in one publish response can be from 0 to queue size (the later can happen if publish interval is longer than sampling interval, so during a publishing interval sampling occurs more than once).

I have updated the zip file, in my testing it reconnects to the server. Although there is problem if the server is not running when the OPC UA Data Logger starts - in this case it does not connect even after the server is started. I will add new issue in this regard later.

On help with development, could you please send me some info about your background to ravil at onewayautomation.com
Thank you, Ravil

**Comment by RavilN** [comment]
Resolved, closing.
