### ISSUE TITLE
run-time error: [14: unable to open database file]

### ISSUE THREAD

**Issue by wmehling** [onewayautomation/ogamma-logger#15]
Hallo,

after starting the ogamma-logger with `docker-compose up` with the latest images I get the following error:

```
ogamma-logger_1    | ConfigDbManager::UpdateInstance: run-time error occurred: [14: unable to open database file].
ogamma-logger_1    | Failed to update instance record in the configuration database
```

The error leads to a partly unresponsive application, as no settings can be stored/deleted.

My setup:
- Windows 10 v1803, no admin-rights
- WSL1 with Ubuntu 18.04
- Docker for Windows mirrored to WSL
- Docker-Compose run as root in WSL 

Any help is appreciated.

Cheers, 
Willy

**Comment by RavilN** [comment]
Hi,
Can you please clarify: do you have Docker Desktop for Windows installed in the host, but instead using it, you run docker installed within WSL?
Looks like this is something caused by file access rights. Can you try to add the line "privileged: true" into the docker-compose.yml file, into the section for ogamma-logger, and let us know if that makes any change?

**Comment by wmehling** [comment]
Thank you for the fast reply.

My Docker runs on Windows and I access the daemon via TCP from the WSL, the first edition WSL does not provide a standalone Docker.

I guess you are right about the file access rights, as on my office PC I have limited access to some folders and no admin rights. Unfortunately, privileged mode did not solve the issue. But in any case it should be a specific problem for my setup and no general issue with the software.

I now set-up the services on a Linux VM with root rights and it work's like a charm.
