### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by alexmc1510** [onewayautomation/ogamma-logger#7]
Hello,

I follow all installation steps but I receive the following error when I run docker-compose:
`ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in ".\..\docker-compose.yml", line 117, column 71`
I am using W10.

Could you help me?

Regards,

**Comment by RavilN** [comment]
Hi,
Thank you for reporting this issue. I think reason is because now just file docker-compose.yml is not enough, content of the whole folder docker should be retrieved. this can be done by cloning of the repository, or if you have it already locally, then pull updates.
And also please note that powershell command "docker-compose up" should be run from folder docker, in order to resolve relative paths to files properly.
It looks that you have modified or not up to date version of the file docker-compose.yml, because currently it has 106 lines, while in your message error happens in line 117.
Please let me know when you resolve the issue or still have problems.

**Comment by RavilN** [comment]
Installation instructions in the ReadMe file has been updated.

**Comment by alexmc1510** [comment]
Thank you. Already installed but not working at all.

**Comment by RavilN** [comment]
Could you please send me more information on this issue: zip of the folder where did you clone this repository, to e-mail support at onewayautomation.com
I cannot reproduce this issue.
Or we can setup web conference to see what is going on (please contact me at the same e-mail).
