### ISSUE TITLE
Error when browsing server

### ISSUE THREAD

**Issue by alexmc1510** [onewayautomation/ogamma-logger#8]
After server configuration, I receive the following error when I try to browse:

`A low level communication error occurred. ("en":"Failed to open transport connection at /home/user/workspace/OpcUaSdk/OpcUaSdk/TcpTransport.cpp/267") To try again, please refresh the page`

**Comment by RavilN** [comment]
Well, it cannot connect to the OPC UA Server.
The server must be accessible from host (docker container, or virtual machine, real PC) wherever Visual Logger is installed. 
If you access it by host  name, that hostname must be resolvable to IP address for example.

If server is running in the container, it is possible to add extra settings to resolve host name in docker-compose.yml (as example it has this: 
    extra_hosts:
      - '${HOST_NAME:-opcuaserver.com}:${HOST_IP_ADDRESS:-75.152.105.54}'
.
Note that if you are running inside of corporate network, you might be not able to access servers located in the Internet due to firewall rules.

**Comment by alexmc1510** [comment]
Hello,
Server is running out of container in opc.tcp://127.0.0.1:49320.
Regards

**Comment by RavilN** [comment]
This explains why Visual Logger cannot connect to it. Because 127.0.0.1 relatively to the container is the container itself, not your host machine.
Your PC should have other IP address(s) too (in local network might be starting by 192.168).
Please try to use that IP address.

**Comment by RavilN** [comment]
If that does not work, then probably you need to allow port 49320 in your host PC firewall settings (although not sure if this is required to access it from container).

**Comment by RavilN** [comment]
In version 0.8.1 after communication error no need to refresh whole page.
Closing the issue.
